### ISSUE TITLE
Game crash when I try to choose terra forged as world gen

### ISSUE THREAD

**Issue by lyssar** [TerraForged/tracker#112]
Hi,
when I try to change the world generation to terra forged my game crashes with the following exception:

> The game crashed whilst mouseclicked event handler
Error: com.terraforged.mod.featuremanager.util.codec.CodecException: null
Exit-Code: -1

Full Log:

<details>
  <summary>Minecraft Crash Report</summary>

> // Hey, that tickles! Hehehe!
> 
> Time: 5/12/21 8:27 PM
> Description: mouseClicked event handler
> 
> com.terraforged.mod.featuremanager.util.codec.CodecException: null
	at com.terraforged.mod.featuremanager.util.codec.CodecException$$Lambda$22671/836355363.get(Unknown Source) ~[?:?] {}
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51] {}
	at com.terraforged.mod.featuremanager.util.codec.Codecs.decodeAndGet(Codecs.java:72) ~[?:1.16.5-0.2.10] {re:classloading}
	at com.terraforged.mod.chunk.settings.StructureSettings.apply(StructureSettings.java:123) ~[?:1.16.5-0.2.10] {re:classloading}
	at com.terraforged.mod.chunk.settings.StructureSettings.validateAndApply(StructureSettings.java:93) ~[?:1.16.5-0.2.10] {re:classloading}
	at com.terraforged.mod.chunk.TFChunkGenerator.<init>(TFChunkGenerator.java:117) ~[?:1.16.5-0.2.10] {re:classloading}
	at com.terraforged.mod.LevelType.createOverworld(LevelType.java:101) ~[?:1.16.5-0.2.10] {re:classloading}
	at com.terraforged.mod.LevelType.createChunkGenerator(LevelType.java:59) ~[?:1.16.5-0.2.10] {re:classloading}
	at com.terraforged.mod.LevelType.createSettings(LevelType.java:71) ~[?:1.16.5-0.2.10] {re:classloading}
	at net.minecraftforge.common.world.ForgeWorldType.createSettings(ForgeWorldType.java:94) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeWorldTypeScreens$GeneratorType.func_241220_a_(ForgeWorldTypeScreens.java:108) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.WorldOptionsScreen.func_239050_a_(WorldOptionsScreen.java:114) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.WorldOptionsScreen$$Lambda$22590/158331947.onPress(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$21854/2136968676.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$21853/757215894.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$18137/147815743.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.16.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$479/747343328.call(Unknown Source) [forge-1.16.5-36.1.16.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

</details>

<details>
  <summary>A detailed walkthrough of the error, its code path and all known details is as follows</summary>

> -- Head --
Thread: Render thread
Stacktrace:
	at com.terraforged.mod.featuremanager.util.codec.CodecException$$Lambda$22671/836355363.get(Unknown Source) ~[?:?] {}
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51] {}
	at com.terraforged.mod.featuremanager.util.codec.Codecs.decodeAndGet(Codecs.java:72) ~[?:1.16.5-0.2.10] {re:classloading}
	at com.terraforged.mod.chunk.settings.StructureSettings.apply(StructureSettings.java:123) ~[?:1.16.5-0.2.10] {re:classloading}
	at com.terraforged.mod.chunk.settings.StructureSettings.validateAndApply(StructureSettings.java:93) ~[?:1.16.5-0.2.10] {re:classloading}
	at com.terraforged.mod.chunk.TFChunkGenerator.<init>(TFChunkGenerator.java:117) ~[?:1.16.5-0.2.10] {re:classloading}
	at com.terraforged.mod.LevelType.createOverworld(LevelType.java:101) ~[?:1.16.5-0.2.10] {re:classloading}
	at com.terraforged.mod.LevelType.createChunkGenerator(LevelType.java:59) ~[?:1.16.5-0.2.10] {re:classloading}
	at com.terraforged.mod.LevelType.createSettings(LevelType.java:71) ~[?:1.16.5-0.2.10] {re:classloading}
	at net.minecraftforge.common.world.ForgeWorldType.createSettings(ForgeWorldType.java:94) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeWorldTypeScreens$GeneratorType.func_241220_a_(ForgeWorldTypeScreens.java:108) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.WorldOptionsScreen.func_239050_a_(WorldOptionsScreen.java:114) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.WorldOptionsScreen$$Lambda$22590/158331947.onPress(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$21854/2136968676.run(Unknown Source) ~[?:?] {}
-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screen.CreateWorldScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$21853/757215894.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$18137/147815743.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.16.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$479/747343328.call(Unknown Source) [forge-1.16.5-36.1.16.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
</details>

Any Ideas what could be the reason? When I remove terraforged I can create a world with any of the remaining generation types. Actually just Biomes of Plenty and the standard once are present

**Comment by dirt-worm** [comment]
I have the same issue, hope it gets resolved :)

**Comment by Won-Ton** [comment]
Similar crash to one that someone else reported and we concluded it was caused by another mod that has added structures. Wasn't clear which.

I'll see if I can improve the error reporting that TF does when it encounters such problems but it's not possible for us to fix things that other mods are doing.

If you can reproduce the crash with just TF installed then feel free to open a new support ticket and in doing so please provide the full debug.log and crash-report (you can drag-drop the files into the input box to upload ;]).

**Comment by lyssar** [comment]
But explain what terraforged does in the main menu before creating anything? I mean I have a bunch of structure mods in my pack sure but biomes of plenty doesn't have any issues in the main menu at all. I am not talking about a generated world the game crashes while trying to switch the generation type in the create new world screen.

The default is biomes of plenty, switching to the next, which is terraforged, crashes the game. Fun fact: all mods worked so far in a previous generated world with terraforged, I added some after I initially created a world for testing. So there where like 0 issues.

**Comment by aminecraftplayerx** [comment]
After a very frustrating couple of hours, I figured out what was causing this. If you have a custom preset that includes structures from mods which are no longer in the instance, it crashes. If that preset is the default, then you can't even get to the world config screen without it crashing.

In detail, I had the mode "repurposed structures" in an instance I was working on. I saved a preset and set it as default. Then every time I tried to create a new world, the game crashed, until I (finally) deleted that preset from the instance's config folder.

BTW, thanks for the great mod, I really like being able to have some more fine tuned control over worldgen.

**Comment by Deltacleic** [comment]
I have the exact same issue, but I don't have any preset saved whatsoever. Similar to the other issues mentioned, it was performing just fine until the next time I load the launcher and attempt to change the world type to "Terraforged" it sends me into a crash. The only thing is that I do not have a custom preset for the generation, (Nothing located in the preset folder either),  as every time I set it differently it crashes.

**Comment by Won-Ton** [comment]
again, that is caused by another mod doing something silently. check you're on latest tf it's better at reporting issues. provide the logs and crash-reporrts if it continues to be an issue as they might let me tell you what mod is the problem
