### ISSUE TITLE
Server seems to get stuck when it's creating terraforged chunks (with no crash reports)

### ISSUE THREAD

**Issue by rakostep** [TerraForged/tracker#117]
Hi there, I'd like to report an issue with TerraForged preventing the server to start. This hasn't happened before I requested a change of node of the server (since it got overloaded). The staff on the server tried their best trouble shooting this and still results the same. I also tested removing some mods that could be interfering with terraforged but none of it worked. I tried looking for crash reports and debug logs for it and it all says similar stuff on the server console. Here's the what the console reflected whenever the crash occurs:

```
20.05 08:51:31 [Server] main/INFO [co.ee.mo.MovingSunflowers/]: Added modded sunflower feature
20.05 08:51:32 [Server] main/INFO [TerraForged/]: Creating TerraForged level settings
20.05 08:51:32 [Server] main/INFO [TerraForged/]: Creating TerraForged chunk-generator from preset Default
20.05 08:51:32 [Server] INFO Exception in thread "main" [08:51:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at java.lang.reflect.Method.invoke(Method.java:498)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: ... 7 more
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.ExceptionInInitializerError
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: at com.terraforged.mod.biome.provider.analyser.BiomeAnalyser$1.<init>(BiomeAnalyser.java:57)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: at com.terraforged.mod.biome.provider.analyser.BiomeAnalyser.<clinit>(BiomeAnalyser.java:56)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: at com.terraforged.mod.biome.provider.TFBiomeProvider.<init>(TFBiomeProvider.java:66)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: at com.terraforged.mod.LevelType.createOverworld(LevelType.java:100)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: at com.terraforged.mod.LevelType.createChunkGenerator(LevelType.java:59)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: at com.terraforged.mod.LevelType.createSettings(LevelType.java:71)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: at net.minecraftforge.common.world.ForgeWorldType.createSettings(ForgeWorldType.java:94)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: at net.minecraft.world.gen.settings.DimensionGeneratorSettings.func_242753_a(DimensionGeneratorSettings.java:214)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: at net.minecraft.server.dedicated.ServerProperties.<init>(SourceFile:72)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: at net.minecraft.server.dedicated.ServerProperties.func_244380_a(SourceFile:76)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: at net.minecraft.server.ServerPropertiesProvider.<init>(SourceFile:14)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: at net.minecraft.server.Main.main(Main.java:98)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:643]: ... 13 more
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.NullPointerException
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:667]: at com.terraforged.engine.world.biome.type.BiomeTypeLoader.generateTypeMap(BiomeTypeLoader.java:78)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:667]: at com.terraforged.engine.world.biome.type.BiomeTypeLoader.<init>(BiomeTypeLoader.java:42)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:667]: at com.terraforged.engine.world.biome.type.BiomeTypeLoader.getInstance(BiomeTypeLoader.java:136)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:667]: at com.terraforged.engine.world.biome.type.BiomeType.init(BiomeType.java:159)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:667]: at com.terraforged.engine.world.biome.type.BiomeType.<clinit>(BiomeType.java:168)
20.05 08:51:32 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:667]: ... 25 more
20.05 08:51:32 [Multicraft] Server shut down (starting)
20.05 08:51:32 [Multicraft] Restarting crashed server in 10 seconds
20.05 08:51:32 [Multicraft] Looks like a crash, check the server console. Return value: 1
20.05 08:51:32 [Multicraft] Server stopped
```

Thank you for your time on reading this.

**Comment by rakostep** [comment]
Hi again Won-Ton, thanks for the clarification over the issue, I'll try doing those and a couple of troubleshooting and get back to you if something new comes up. Thanks for the mod btw.

**Comment by rakostep** [comment]
alright, Hi again Won-Ton, I did the bit on your advice on replacing the corrupted file, and also checked on the configs on other mods that does some world gen, but seems like it gets the same error. Though, I did some check on logs before the world generation occurs, I hope this adds some info:

```
21.05 08:48:57 [Server] modloading-worker-12/INFO [sc.ba.Bamboo2/]: Config done.
21.05 08:48:58 [Server] modloading-worker-1/INFO [TerraForged/]: Environment: dev=false, stable=true, vanilla=false
21.05 08:48:58 [Server] modloading-worker-1/INFO [TerraForged/]: Signature:  7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
21.05 08:48:58 [Server] modloading-worker-1/INFO [TerraForged/]: Trust Data: CN=TerraForged self-signed
21.05 08:48:58 [Server] modloading-worker-1/INFO [TerraForged/]: Initializing tags
21.05 08:48:58 [Server] modloading-worker-10/FATAL [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
21.05 08:49:01 [Server] main/INFO [ne.or.un.Unearthed/]: UE: Blocks registered!
21.05 08:49:01 [Server] main/INFO [ne.or.un.Unearthed/]: UE: Items registered!
21.05 08:49:02 [Server] main/INFO [TerraForged/]: Registering level types
```

**Comment by Won-Ton** [comment]
Hi no unfortuntely the extra log snippet doesn't tell me anything.

If the only thing that has changed since you had a working server is that your host upgraded/transfered it to a different machine then it suggests that something is up with the new machine. I can't help with that sorry :(
