### ISSUE TITLE
exception stopping a server

### ISSUE THREAD

**Issue by k1r0s** [TerraForged/tracker#134]
Exception caught during firing event: com/terraforged/mod/profiler/ProfilerPrinter

after generating a world with chunk pregenerator

forge: forge-1.16.5-36.1.32

```
java.lang.NoClassDefFoundError: com/terraforged/mod/profiler/ProfilerPrinter
	at com.terraforged.mod.profiler.Profiler.dump(Profiler.java:142)
	at com.terraforged.mod.profiler.Profiler.dump(Profiler.java:132)
	at com.terraforged.mod.server.ServerEvents.serverStop(ServerEvents.java:46)
	at net.minecraftforge.eventbus.ASMEventHandler_86_ServerEvents_serverStop_FMLServerStoppedEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:124)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ClassNotFoundException: com.terraforged.mod.profiler.ProfilerPrinter
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 11 more
	Suppressed: java.lang.ClassNotFoundException: Failed to find class bytes for com.terraforged.mod.profiler.ProfilerPrinter
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:260)
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
		... 12 more
	Caused by: java.nio.channels.ClosedChannelException
		at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:156)
		at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:353)
		at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:58)
		at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1231)
		at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1226)
		at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.initDataPos(ZipFileSystem.java:2261)
		at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2199)
		at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2146)
		at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:252)
		... 14 more

```

**Comment by Won-Ton** [comment]
This is an issue between forge and the java version you're using.  Make sure you're on a supported version of java (ie java 8)

**Comment by k1r0s** [comment]
If I understand correctly java 8 is no longer supported by the forge community

**Comment by Won-Ton** [comment]
Nope that's the **only** version forge supports
