### ISSUE TITLE
just had this crash on 1.16.5 forge 36.1.31 with Dynamic trees

### ISSUE THREAD

**Issue by Mr-Syntax** [TerraForged/tracker#138]
[02:00:44] [Worker-Main210/WARN]: Worker-Main210 died
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/terraforged/mod/profiler/crash/CrashReportBuilder
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$33896/100452417.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.NoClassDefFoundError: com/terraforged/mod/profiler/crash/CrashReportBuilder
	at com.terraforged.mod.client.ClientCrashHandler.crash(ClientCrashHandler.java:54) ~[?:1.16.5-0.2.12]
	at com.terraforged.mod.profiler.crash.CrashHandler.handle(CrashHandler.java:40) ~[?:1.16.5-0.2.12]
	at com.terraforged.mod.chunk.TFChunkGenerator.func_242707_a(TFChunkGenerator.java:191) ~[?:1.16.5-0.2.12]
	at net.minecraft.world.chunk.ChunkStatus.func_222586_d(ChunkStatus.java:41) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2356/2037228858.doWork(Unknown Source) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:675) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$33898/1726822134.apply(Unknown Source) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:673) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$33883/173225417.apply(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51]
	... 12 more
[02:00:44] [Worker-Main211/INFO]:  - Erosion decorator enabled
[02:00:44] [Worker-Main211/INFO]:  - Natural snow decorator enabled
[02:00:44] [Worker-Main211/INFO]:  - Erosion decorator enabled
[02:00:44] [Worker-Main211/INFO]:  - Natural snow decorator enabled
[02:00:44] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$33542/755535424.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NoClassDefFoundError: com/terraforged/mod/profiler/crash/CrashReportBuilder
	at com.terraforged.mod.client.ClientCrashHandler.crash(ClientCrashHandler.java:54) ~[?:1.16.5-0.2.12]
	at com.terraforged.mod.profiler.crash.CrashHandler.handle(CrashHandler.java:40) ~[?:1.16.5-0.2.12]
	at com.terraforged.mod.chunk.TFChunkGenerator.func_242707_a(TFChunkGenerator.java:191) ~[?:1.16.5-0.2.12]
	at net.minecraft.world.chunk.ChunkStatus.func_222586_d(ChunkStatus.java:41) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2356/2037228858.doWork(Unknown Source) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:675) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$33898/1726822134.apply(Unknown Source) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:673) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$33883/173225417.apply(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$33896/100452417.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51]
[02:00:44] [Worker-Main211/INFO]:  - Erosion decorator enabled
[02:00:44] [Worker-Main211/INFO]:  - Natural snow decorator enabled
[02:00:44] [Worker-Main215/WARN]: Worker-Main215 died
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/terraforged/mod/profiler/crash/CrashReportBuilder
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$33896/100452417.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.NoClassDefFoundError: com/terraforged/mod/profiler/crash/CrashReportBuilder
	at com.terraforged.mod.client.ClientCrashHandler.crash(ClientCrashHandler.java:54) ~[?:1.16.5-0.2.12]
	at com.terraforged.mod.profiler.crash.CrashHandler.handle(CrashHandler.java:40) ~[?:1.16.5-0.2.12]
	at com.terraforged.mod.chunk.TFChunkGenerator.func_242707_a(TFChunkGenerator.java:191) ~[?:1.16.5-0.2.12]
	at net.minecraft.world.chunk.ChunkStatus.func_222586_d(ChunkStatus.java:41) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2356/2037228858.doWork(Unknown Source) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:675) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$33898/1726822134.apply(Unknown Source) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:673) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$33883/173225417.apply(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51]
	... 12 more
[02:00:44] [Worker-Main210/ERROR]: Caught exception in thread Thread[Worker-Main210,1,SERVER]
java.lang.NoClassDefFoundError: com/terraforged/mod/profiler/crash/CrashReportBuilder
	at com.terraforged.mod.client.ClientCrashHandler.crash(ClientCrashHandler.java:54) ~[?:1.16.5-0.2.12]
	at com.terraforged.mod.profiler.crash.CrashHandler.handle(CrashHandler.java:40) ~[?:1.16.5-0.2.12]
	at com.terraforged.mod.chunk.TFChunkGenerator.func_242707_a(TFChunkGenerator.java:191) ~[?:1.16.5-0.2.12]
	at net.minecraft.world.chunk.ChunkStatus.func_222586_d(ChunkStatus.java:41) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2356/2037228858.doWork(Unknown Source) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:675) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$33898/1726822134.apply(Unknown Source) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:673) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$33883/173225417.apply(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$33896/100452417.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51]
[02:00:44] [Worker-Main215/ERROR]: Caught exception in thread Thread[Worker-Main215,1,SERVER]
java.lang.NoClassDefFoundError: com/terraforged/mod/profiler/crash/CrashReportBuilder
	at com.terraforged.mod.client.ClientCrashHandler.crash(ClientCrashHandler.java:54) ~[?:1.16.5-0.2.12]
	at com.terraforged.mod.profiler.crash.CrashHandler.handle(CrashHandler.java:40) ~[?:1.16.5-0.2.12]
	at com.terraforged.mod.chunk.TFChunkGenerator.func_242707_a(TFChunkGenerator.java:191) ~[?:1.16.5-0.2.12]
	at net.minecraft.world.chunk.ChunkStatus.func_222586_d(ChunkStatus.java:41) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2356/2037228858.doWork(Unknown Source) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:675) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$33898/1726822134.apply(Unknown Source) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:673) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$33883/173225417.apply(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$33896/100452417.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51]

**Comment by Won-Ton** [comment]
need full logs to be sure but looks like you're not running a version of java that forge supports (java8)
