### ISSUE TITLE
Problems with structure generation

### ISSUE THREAD

**Issue by Mr-Syntax** [TerraForged/tracker#149]
I cannot confirm 100% that this is terraforgeds fault but something weird is going on

for instance, if i add or remove journey map or xaroes minimap or enhanced visuals certain structures just stop spawning
then sometimes everything just stops spawning untill i reload the game
another thing is all of a sudden the spacing between structures seems to have quadrupled and i have no idea why...
if you could get the Dungeons now loading data pack working in here aswell that would be appreciated, sometimes it will say its working but i never find any structures related to it :-/

link to the pack: https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by Mr-Syntax** [comment]
okay it is definently terraforged

when i use my custom setup its all broken, then i tried loading the default preset and it worked.
then i wanted to just fiddle with the settings on the biome generation on the default preset but when i opened it and checked the structure tab no structures were registered

**Comment by Won-Ton** [comment]
can you provide logs and clear steps to reproduce with just forge, TF, and whatever structure mod is going missing

**Comment by Mr-Syntax** [comment]
okay first download the pack

then try locating the following in creative:

Dark caverens forgotten tower
Dungeon Crawl
Dungeons_arise
Endrem:Castle

in no cases will all the structures generate, even if i teleport 100000 blocks in one direction and do a new search it wont show up, then when i close the map go in to the terraforged preset again and move the slider on the Endrem:castle it will sometimes crash when i try to create the map

sometimes then when it doesent crash and i go into the preset all structures are gone, and thats on the default preset aswell 

super elusive bug i gotta say, first i thought it was the combination of the other mods and that definently has something to say but when i use default gen they are all there.

i sadly didnt have blame on when it happend but i will try to reproduce tonight and provide you with the logs

**Comment by Mr-Syntax** [comment]
Clearification, when i detected a structure wasent generating, i would go into the terraforged presets and either move the slider on the structure that isent generating or load the default preset and load my preset again.

and in most cases when i do this it crashes during worldgen

**Comment by Won-Ton** [comment]
can you post the crash-reports and corresponding logs please. sounds like a third party mod is causing issues. not sure if related to the structure thing

**Comment by Won-Ton** [comment]
Ok yeah you need to report this to the modpack creator. They have a mod/datapack installed that is either overriding, removing or breaking the structure settings that are being given to terraforged.

Similarly for the crash you need to report to the modpack creator.

**Comment by Won-Ton** [comment]
If you/they can reproduce with just forge, terraforged and a minimal sample of structure mods, and it there appears to be an issue with TF feel free to open a ticket but please provide clear steps to reproduce, logs and crash-reports

**Comment by Won-Ton** [comment]
I'd suggest you strip things back to basics and methodically add in mods and routinely test the setup to make sure things are as expected. I'm biased so I'd suggest you start with world-gen stuff first.

Maybe try the 'blame' mod - that spews out a bunch of error messages for things that mods commonly do wrong that break worldgen.

**Comment by Mr-Syntax** [comment]
i got this from the normal logs, gonna try to crash it with blame on now

[04:13:47] [Server thread/ERROR]: Exception caught during firing event: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@45f1c2a3 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7cfa464[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 177]
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.terraforged.mod.biome.spawn.SpawnHandler createSpawn(Lnet/minecraftforge/event/world/WorldEvent$CreateSpawnPosition;)V
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@45f1c2a3 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7cfa464[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 177]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:573)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleAtFixedRate(Executors.java:735)
	at com.terraforged.engine.concurrent.thread.ThreadPools.scheduleRepeat(ThreadPools.java:79)
	at com.terraforged.engine.concurrent.cache.CacheManager.schedule(CacheManager.java:42)
	at com.terraforged.engine.concurrent.cache.Cache.<init>(Cache.java:56)
	at com.terraforged.engine.world.rivermap.RiverCache.<init>(RiverCache.java:37)
	at com.terraforged.engine.world.continent.simple.ContinentGenerator.<init>(ContinentGenerator.java:84)
	at com.terraforged.engine.world.continent.simple.MultiContinentGenerator.<init>(MultiContinentGenerator.java:33)
	at com.terraforged.engine.world.continent.ContinentType$1.create(ContinentType.java:38)
	at com.terraforged.engine.world.heightmap.Heightmap.<init>(Heightmap.java:135)
	at com.terraforged.engine.world.WorldGeneratorFactory.<init>(WorldGeneratorFactory.java:38)
	at com.terraforged.engine.world.GeneratorContext$$Lambda$26754/1725744615.apply(Unknown Source)
	at com.terraforged.engine.concurrent.task.LazySupplier.lambda$factory$0(LazySupplier.java:52)
	at com.terraforged.engine.concurrent.task.LazySupplier$$Lambda$26755/1715333184.get(Unknown Source)
	at com.terraforged.engine.concurrent.task.LazySupplier.create(LazySupplier.java:40)
	at com.terraforged.engine.concurrent.task.LazyCallable.call(LazyCallable.java:71)
	at com.terraforged.engine.concurrent.task.LazyCallable.get(LazyCallable.java:111)
	at com.terraforged.engine.concurrent.task.LazySupplier.lambda$supplied$1(LazySupplier.java:56)
	at com.terraforged.engine.concurrent.task.LazySupplier$$Lambda$26753/1438949176.get(Unknown Source)
	at com.terraforged.engine.concurrent.task.LazySupplier.create(LazySupplier.java:40)
	at com.terraforged.engine.concurrent.task.LazyCallable.call(LazyCallable.java:71)
	at com.terraforged.engine.concurrent.task.LazyCallable.get(LazyCallable.java:111)
	at com.terraforged.mod.biome.spawn.SpawnHandler.getSearchCenter(SpawnHandler.java:82)
	at com.terraforged.mod.biome.spawn.SpawnHandler.createSpawn(SpawnHandler.java:54)
	at net.minecraftforge.eventbus.ASMEventHandler_1144_SpawnHandler_createSpawn_CreateSpawnPosition.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2475/2022966218.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.onCreateWorldSpawn(ForgeEventFactory.java:522)
	at net.minecraft.server.MinecraftServer.func_240786_a_(MinecraftServer.java:391)
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:344)
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:308)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:86)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$29025/1917392236.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[04:13:47] [Server thread/FATAL]: Preparing crash report with UUID a9063780-e79c-4de8-a417-84188ea685b0
[04:13:47] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception initializing level
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:357) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:308) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:86) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$29025/1917392236.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@45f1c2a3 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7cfa464[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 177]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) ~[?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:573) ~[?:1.8.0_51]
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleAtFixedRate(Executors.java:735) ~[?:1.8.0_51]
	at com.terraforged.engine.concurrent.thread.ThreadPools.scheduleRepeat(ThreadPools.java:79) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.concurrent.cache.CacheManager.schedule(CacheManager.java:42) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.concurrent.cache.Cache.<init>(Cache.java:56) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.world.rivermap.RiverCache.<init>(RiverCache.java:37) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.world.continent.simple.ContinentGenerator.<init>(ContinentGenerator.java:84) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.world.continent.simple.MultiContinentGenerator.<init>(MultiContinentGenerator.java:33) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.world.continent.ContinentType$1.create(ContinentType.java:38) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.world.heightmap.Heightmap.<init>(Heightmap.java:135) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.world.WorldGeneratorFactory.<init>(WorldGeneratorFactory.java:38) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.world.GeneratorContext$$Lambda$26754/1725744615.apply(Unknown Source) ~[?:?]
	at com.terraforged.engine.concurrent.task.LazySupplier.lambda$factory$0(LazySupplier.java:52) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.concurrent.task.LazySupplier$$Lambda$26755/1715333184.get(Unknown Source) ~[?:?]
	at com.terraforged.engine.concurrent.task.LazySupplier.create(LazySupplier.java:40) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.concurrent.task.LazyCallable.call(LazyCallable.java:71) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.concurrent.task.LazyCallable.get(LazyCallable.java:111) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.concurrent.task.LazySupplier.lambda$supplied$1(LazySupplier.java:56) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.concurrent.task.LazySupplier$$Lambda$26753/1438949176.get(Unknown Source) ~[?:?]
	at com.terraforged.engine.concurrent.task.LazySupplier.create(LazySupplier.java:40) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.concurrent.task.LazyCallable.call(LazyCallable.java:71) ~[?:1.16.5-0.2.15]
	at com.terraforged.engine.concurrent.task.LazyCallable.get(LazyCallable.java:111) ~[?:1.16.5-0.2.15]
	at com.terraforged.mod.biome.spawn.SpawnHandler.getSearchCenter(SpawnHandler.java:82) ~[?:1.16.5-0.2.15]
	at com.terraforged.mod.biome.spawn.SpawnHandler.createSpawn(SpawnHandler.java:54) ~[?:1.16.5-0.2.15]
	at net.minecraftforge.eventbus.ASMEventHandler_1144_SpawnHandler_createSpawn_CreateSpawnPosition.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2475/2022966218.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.onCreateWorldSpawn(ForgeEventFactory.java:522) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240786_a_(MinecraftServer.java:391) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:344) ~[?:?]
	... 6 more

**Comment by Mr-Syntax** [comment]
[crash-2021-09-12_04.39.45-server.txt](https://github.com/TerraForged/tracker/files/7148891/crash-2021-09-12_04.39.45-server.txt)

**Comment by Mr-Syntax** [comment]
okay this is interesting that crash is indicating that dynamic lights is the cause but this crash was made just like the other where i load into a new seed, dungeons crawl isent generating so i go out fiddle with the slider on dungeon crawl in the terraforged preset and then when i try to make a new seed it crashes

**Comment by Mr-Syntax** [comment]
[crash-2021-09-12_06.12.53-server.txt](https://github.com/TerraForged/tracker/files/7148987/crash-2021-09-12_06.12.53-server.txt)

okay now i got it to do it again and this is definently a terraforged crash

something really weird is going on with the structure registration and im pretty certain  thats whats crashing it

not to be ungrateful or anything but in a future version, could you consider redoing the structure spawn system?? if we could just have a spacing range ex 30-60 chunks, then it attempts to spawn once every 30-60 chunks from the structure pool, and then we can just set weights for the dungeons or % chances or something i think this could be more efficient.

**Comment by Mr-Syntax** [comment]
[crash-2021-09-12_07.31.27-server.txt](https://github.com/TerraForged/tracker/files/7149043/crash-2021-09-12_07.31.27-server.txt)

**Comment by Mr-Syntax** [comment]
i think it might have something to do with the supplementaries mod as i removed it everything suddenly worked again

**Comment by Mr-Syntax** [comment]
okay yeah im pretty certain its actually supplementaries, it has caused the weirdest bugs but it never shows up in logs or crashes it directly, truly elusive

the reason i noticed it was because i got stuff working with the newest supplementaries but that breaks immersive portals, but then i removed it and everything seems to work now :D
