### ISSUE TITLE
Crashes Server potentially caused by Terraforged

### ISSUE THREAD

**Issue by TechniumUnlimited** [TerraForged/tracker#15]
This occurs and spams this sort of debug output for a while until the server hangs long enough to shut itself down..
I saw a similar issue reported in Yung's Caves but he says it definitely isn't his mod causing it, and I see terraforged mentioned here, as well as traverse, among several other errors that you can see in the debug log.. (only the part where things go sour because it became far too large even for gist...)
https://gist.github.com/TechniumUnlimited/a7e1ef6b369a0b47bf143ef1928bfa8f

and my crash report here shows performant and... strangely, bees, worldlighting as possible culprits... https://pastebin.com/NkAA5PKY

```[17Jan2021 21:07:57.974] [Worker-Main-39/DEBUG] [FeatureManager/Serializer]: Unable to serialize feature in biome: traverse:snowy_high_coniferous_forest
[17Jan2021 21:07:57.974] [Worker-Main-39/DEBUG] [FeatureManager/]: Unable to determine issues. See stacktrace:
java.lang.NullPointerException: null
	at java.util.function.Function.lambda$andThen$1(Unknown Source) ~[?:1.8.0_261]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$getCodec$10(KeyDispatchCodec.java:123) ~[?:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[?:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.getCodec(KeyDispatchCodec.java:123) ~[?:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$new$0(KeyDispatchCodec.java:46) ~[?:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:79) ~[?:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?]
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[?:?]
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$8.encode(RecordCodecBuilder.java:379) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$9.encode(RecordCodecBuilder.java:443) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$4.encode(RecordCodecBuilder.java:224) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$6.encode(RecordCodecBuilder.java:298) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[?:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?]
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[?:?]
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?]
	at com.mojang.serialization.MapEncoder$1.encode(MapEncoder.java:26) ~[?:?]
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:92) ~[?:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?]
	at net.minecraft.util.registry.RegistryKeyCodec.encode(SourceFile:44) ~[?:?]
	at net.minecraft.util.registry.RegistryKeyCodec.encode(SourceFile:13) ~[?:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?]
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[?:?]
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$4.encode(RecordCodecBuilder.java:222) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[?:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?]
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[?:?]
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?]
	at com.mojang.serialization.MapEncoder$1.encode(MapEncoder.java:26) ~[?:?]
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:92) ~[?:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?]
	at com.terraforged.mod.featuremanager.util.codec.Codecs.encode(Codecs.java:86) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.featuremanager.util.codec.Codecs.encode(Codecs.java:96) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.featuremanager.FeatureSerializer.serialize(FeatureSerializer.java:44) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.featuremanager.modifier.FeatureModifiers.getFeature(FeatureModifiers.java:103) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.featuremanager.FeatureManager.compute(FeatureManager.java:122) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.featuremanager.FeatureManager.create(FeatureManager.java:98) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.SetupFactory.createFeatureManager(SetupFactory.java:138) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.GeneratorResources.<init>(GeneratorResources.java:62) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.GeneratorResources.lambda$factory$0(GeneratorResources.java:74) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.engine.concurrent.task.LazySupplier.lambda$factory$0(LazySupplier.java:52) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.engine.concurrent.task.LazySupplier.create(LazySupplier.java:40) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.engine.concurrent.task.LazyCallable.call(LazyCallable.java:68) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.engine.concurrent.task.LazyCallable.get(LazyCallable.java:107) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.TFChunkGenerator.queueChunk(TFChunkGenerator.java:338) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.TFChunkGenerator.queueChunk(TFChunkGenerator.java:334) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.generator.StructureGenerator.generateStructureStarts(StructureGenerator.java:61) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.TFChunkGenerator.func_242707_a(TFChunkGenerator.java:184) ~[terraforged:1.16.4-0.2.0-RC-2]
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$2(ChunkStatus.java:41) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:522) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) [?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) [?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) [?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]

**Comment by TechniumUnlimited** [comment]
I also reference this issue in Traverse's github here: https://github.com/MysticMods/Traverse/issues/38

**Comment by TechniumUnlimited** [comment]
After further inspection of the debug log, it seems it also references problems serializing even vanilla minecraft biomes - so it seems less likely to me that it is a specific biome mod's fault, and more likely it is performant or terraforged

**Comment by noobanidus** [comment]
Can you try installing Blame by TelepathicGrunt? That might give a bigger hint as to what the issue is. It appears to be a feature that is being added to a bunch of biomes isn't serializable/is causing a null pointer for some reason.

**Comment by TechniumUnlimited** [comment]
I do infact have blame and unfortunately at least afai saw, no blame reports were generated related to the issue at the time of the issue

**Comment by noobanidus** [comment]
I'd recommend TerraForged update the FeatureManager's error message to specify *which* feature cannot be serialized properly as it's impossible to tell from this. The exception itself seems to be just a wrapper around the call to serializing with a try/catch block.

**Comment by TechniumUnlimited** [comment]
The last result for blame's reporting prior to the crashing was this message:
`[17Jan2021 21:08:00.657] [Server thread/DEBUG] [mixin/]: Mixing WorldEntitySpawnerMixin from blame.mixins.json into net.minecraft.world.spawner.WorldEntitySpawner`

**Comment by TechniumUnlimited** [comment]
Reloaded the world and found that despite those errors being spammed in the debug log,
the game continues to function for much longer, I still see the errors, and the server did hang eventually - I had a suspicion that it was caused by me breaking a pams harvest craft tree's fruit, but it did not hang on that action this time, instead it hanged when I died due to bees, but I was running around a bit when that happened so it may have caused worldgen related issues..

**Comment by TechniumUnlimited** [comment]
Well I found this in reference to the same error, which points to applied energistic's meteorites as the cause (and removing them resolved the issue) - I will try and see if I can reproduce this fix, but I'm not quite convinced. It could be very rare, as I found this issue on AE2's github, and have BYG and AE2 installed, so it is possible. Its hard to explore around the area to see if a meteorite is around though to know for sure:

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4870

**Comment by TechniumUnlimited** [comment]
Well would you look at that, I removed AE2 to see if world could work now, and sure enough in the chunk I was loaded in at (or one of the surrounding ones ofc), there was a meteorite:

![image](https://user-images.githubusercontent.com/29348969/104881879-f2a53d00-5916-11eb-9e1c-615aa7b7d69c.png)

I will close this issue now as it is quite clear that it was AE2's fault now.

**Comment by noobanidus** [comment]
I would say that TerraForged needs to specify what feature it can't serialize rather than just the biome.

**Comment by TechniumUnlimited** [comment]
True, that is an issue remaining, I am not sure if the two issues were related from the start however, or causing/contributing to the problem - if you'd like I can start a new issue for that specific serialization problem though

**Comment by TechniumUnlimited** [comment]
hmm.. In fact, I can't seem to find the errors in the latest debug log (after having removed AE2) - It may be an issue that only appears in situations like the one above

**Comment by Won-Ton** [comment]
> I would say that TerraForged needs to specify what feature it can't serialize rather than just the biome.

The whole point is it _can't_ specify which feature is failing because the feature is not set up correctly or has not been registered. Printing the object to string doesn't provide any context because ConfiguredFeature doesn't override toStrong. The biome name is all we concretely know

Failing to serialize doesn't break anything though - that's why it's logged at debug level rather than error/warn.
It is a problem and an error on someone's part, but not a critical one.

**Comment by Won-Ton** [comment]
As has been concluded already, the actual crash is unrelated. It's another mod calling unsafe methods inside of feature-generation that results in another chunk being requested thus locking the server up
