### ISSUE TITLE
[1.18.1] Netty Registry Disconnect on Server Join

### ISSUE THREAD

**Issue by red2blue** [TerraForged/tracker#174]
After going down through my modlist, its been determine that TF is causing issues when attempting to join my dedicated server in my modpack I am building. I'm pretty sure its not only because of terraforged, but I believe there to be some sort of mod conflict. 
Client latest; https://pastebin.com/LhjLaWHn
Server latest; https://pastebin.com/e0t40mKH

```java
[06:54:12] [Server thread/INFO]: DaddyDanked[/70.180.147.186:61763] logged in with entity id 415 at (-85.5, 72.0, 50.5)
[06:54:12] [Netty Epoll Server IO #2/ERROR]: Error encoding packet
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.RegistryAccess$RegistryData.m_123111_()" because the return value of "java.util.Map.get(Object)" is null
        at net.minecraft.core.RegistryAccess$RegistryHolder.m_175525_(RegistryAccess.java:186) ~[server-1.18.1-20211210.034407-srg.jar%23254!:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at net.minecraft.core.RegistryAccess$RegistryHolder.m_123135_(RegistryAccess.java:187) ~[server-1.18.1-20211210.034407-srg.jar%23254!:?]
        at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-4.0.26.jar%2329!:?]
        at com.mojang.serialization.Codec$2.encode(Codec.java:76) ~[datafixerupper-4.0.26.jar%2329!:?]
        at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[datafixerupper-4.0.26.jar%2329!:?]
        at net.minecraft.network.FriendlyByteBuf.m_130059_(FriendlyByteBuf.java:97) ~[server-1.18.1-20211210.034407-srg.jar%23254!:?]
        at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5779_(ClientboundLoginPacket.java:66) ~[server-1.18.1-20211210.034407-srg.jar%23254!:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:42) ~[server-1.18.1-20211210.034407-srg.jar%23254!:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:15) ~[server-1.18.1-20211210.034407-srg.jar%23254!:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at net.minecraft.network.Connection.m_178303_(Connection.java:202) ~[server-1.18.1-20211210.034407-srg.jar%23254!:?]
        at net.minecraft.network.Connection.lambda$sendPacket$5(Connection.java:191) ~[server-1.18.1-20211210.034407-srg.jar%23254!:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[06:54:12] [Server thread/INFO]: DaddyDanked joined the game
[06:54:12] [Server thread/INFO]: [Progressive Bosses] DaddyDanked spawned withers counter was below the set 'Starting Difficulty', Has been increased to match 'Starting Difficulty'
[06:54:12] [Server thread/INFO]: [Progressive Bosses] DaddyDanked killed dragons counter was below the set 'Starting Difficulty', Has been increased to match 'Starting Difficulty'
[06:54:12] [Server thread/INFO]: [Progressive Bosses] DaddyDanked first spawned. Set First Dragon to 1
[06:54:13] [Server thread/INFO]: New Server UUID 6ea016ad-477e-4e7b-a3d5-f638bda2da8e
[06:54:13] [Server thread/INFO]: Syncing config to DaddyDanked (f2ff4810-9a32-4e04-ac5c-a25e3ebf916c)
[06:54:13] [Server thread/INFO]: DaddyDanked lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.core.RegistryAccess$RegistryData.m_123111_()" because the return value of "java.util.Map.get(Object)" is null
```

**Comment by CreativeRealms** [comment]
Read the changelog and stop opening bug reports.

This is a very early build of TerraForged for 1.18.1.
Please consider it an early-stage development 'snapshot' (much like those that Mojang release). **Please do not report bugs or compatibility issues using this version.** We know it is not stable or well tested yet, but it will become so as development continues.

As such:
-It is is not suitable for modpack design/creation.
-It probably is not suitable for serious survival play.
-Future updates will probably not work with worlds created on this version.
-Many features and customisation options are not yet implemented.
-Mod and datapack compatibility is not thoroughly tested.
-Some vanilla world-gen features have not yet been implemented.
-This version does not provide a world-type option (when you create a new world TerraForged should get used automatically).

**Comment by red2blue** [comment]
I truly wish I read the changelog. I would have just saved 3 hours. anyways, apologies for the last bug report.

**Comment by itsdinkd** [comment]
With the latest update, is it suitable for modpacks now?

**Comment by CreativeRealms** [comment]
> With the latest update, is it suitable for modpacks now?

No.

**Comment by itsdinkd** [comment]
So doesn't say it this time in your change log for 1.18.2, this still happens, but on 1.18.2 in dedicated servers upon joining.  Should probably fix something that existed for 5 months or write in your change log that its not compatible for servers / modpacks
