### ISSUE TITLE
Crash with totw

### ISSUE THREAD

**Issue by DavyCricket** [TerraForged/tracker#176]
I'm not entirely sure if was addressed already, but the mod seems to crash sometimes when towers of the wild is installed. Here's the crashlog

Description: generating structure starts (TerraForged World-Gen)

java.lang.NullPointerException: generating structure starts (TerraForged World-Gen)
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_51] {}
	at com._idrae.towers_of_the_wild.structures.AbstractTowerStructure.alreadyIsTower(AbstractTowerStructure.java:66) ~[?:1.16.3-2.0.0] {re:classloading}
	at com._idrae.towers_of_the_wild.structures.AbstractTowerStructure.func_230363_a_(AbstractTowerStructure.java:44) ~[?:1.16.3-2.0.0] {re:classloading}
	at com._idrae.towers_of_the_wild.structures.AbstractTowerStructure.func_230363_a_(AbstractTowerStructure.java:20) ~[?:1.16.3-2.0.0] {re:classloading}
	at net.minecraft.world.gen.feature.structure.Structure.func_242785_a(Structure.java:222) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.gen.feature.StructureFeature.func_242771_a(SourceFile:35) ~[?:?] {re:classloading}
	at com.terraforged.mod.chunk.generator.StructureGenerator.generate(StructureGenerator.java:87) ~[?:1.16.5-0.2.15] {re:classloading}
	at com.terraforged.mod.chunk.generator.StructureGenerator.generateStructureStarts(StructureGenerator.java:76) ~[?:1.16.5-0.2.15] {re:classloading}
	at com.terraforged.mod.chunk.TFChunkGenerator.func_242707_a(TFChunkGenerator.java:196) [?:1.16.5-0.2.15] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_222586_d(ChunkStatus.java:41) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2173/926295246.doWork(Unknown Source) [?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:access.ChunkManagerAccess,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$18641/2096315330.apply(Unknown Source) [?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) [datafixerupper-4.0.26.jar:?] {}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:access.ChunkManagerAccess,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$18638/1076264105.apply(Unknown Source) [?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) [?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) [?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) [?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$18579/873528642.run(Unknown Source) [?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) [?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) [?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) [?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51] {}

**Comment by Won-Ton** [comment]
The crash is occurring inside tow's code
