### ISSUE TITLE
TerraForge 1.16 Crashing On Start

### ISSUE THREAD

**Issue by TehAngryBird345** [TerraForged/tracker#203]
My game is crashing whenever I am loading up a Terraforged world type. It always works fine if I don’t play on a terraforged world. I tried using lower quality settings, but it still crashes. Usually it takes a few seconds after loading in. I am using a few other mods, those being:

Distant Horizons
Track API
Immersive Engineering
Immersive Railroading
Universal Mod Core
Controllable
Optifine

Any help to try and prevent it from crashing is highly appreciated.

**Comment by Won-Ton** [comment]
I'd need to see the logs and the crash report to be able to more accurately diagnose, but DistantHorizons has often caused crashes with world-gen mods so maybe check you're on the latest version of it and/or see if they have any settings that improve compatibility with mods and/or try running without it.

**Comment by TehAngryBird345** [comment]
This is the crash report. Distant Horizons has seemed to be buggy with the mod before it crashes. It seems like I'm running the latest version of Distant Horizons for 1.16.5 so it might be an issue with that version. hopefully the crash report helps.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/8/23 4:07 PM
Description: generating features & structures (TerraForged World-Gen)

com.terraforged.mod.profiler.watchdog.UncheckedException: Critical error detected whilst generating Feature [minecraft:count,minecraft:decorated,minecraft:fern,minecraft:grass,minecraft:heightmap_spread_double,minecraft:random_patch,minecraft:simple_block_placer,minecraft:square,minecraft:weighted_state_provider]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1353) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_51] {}
	at net.minecraft.util.WeightedList.func_226318_b_(SourceFile:60) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.blockstateprovider.WeightedBlockStateProvider.func_225574_a_(SourceFile:42) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.RandomPatchFeature.func_241855_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.RandomPatchFeature.func_241855_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_242772_a(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature$$Lambda$8288/1420974530.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:22) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_242772_a(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature$$Lambda$8288/1420974530.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:1.8.0_51] {}
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:22) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading}
	at com.terraforged.mod.chunk.generator.FeatureGenerator.decorate(FeatureGenerator.java:166) ~[?:1.16.5-0.2.16] {re:classloading}
	at com.terraforged.mod.chunk.generator.FeatureGenerator.decorate(FeatureGenerator.java:106) ~[?:1.16.5-0.2.16] {re:classloading}
	at com.terraforged.mod.chunk.generator.FeatureGenerator.generateFeatures(FeatureGenerator.java:88) ~[?:1.16.5-0.2.16] {re:classloading}
	at com.terraforged.mod.chunk.TFChunkGenerator.func_230351_a_(TFChunkGenerator.java:250) [?:1.16.5-0.2.16] {re:classloading}
	at forge.com.seibel.lod.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:43) [?:?] {re:classloading}
	at forge.com.seibel.lod.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:432) [?:?] {re:classloading}
	at forge.com.seibel.lod.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:332) [?:?] {re:classloading}
	at forge.com.seibel.lod.common.wrappers.worldGeneration.GenerationEvent.lambda$new$0(GenerationEvent.java:45) [?:?] {re:classloading}
	at forge.com.seibel.lod.common.wrappers.worldGeneration.GenerationEvent$$Lambda$7950/351221388.run(Unknown Source) [?:?] {}
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51] {}
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51] {}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Current Chunk --
Details:
	Pos: [210, 228]
	Status: features
	Structure Starts: [minecraft:mineshaft, minecraft:ruined_portal, minecraft:stronghold]
	Structure Refs: [minecraft:bastion_remnant, minecraft:buried_treasure, minecraft:desert_pyramid, minecraft:endcity, minecraft:fortress, minecraft:igloo, minecraft:jungle_pyramid, minecraft:mansion, minecraft:mineshaft, minecraft:monument, minecraft:nether_fossil, minecraft:ocean_ruin, minecraft:pillager_outpost, minecraft:ruined_portal, minecraft:shipwreck, minecraft:stronghold, minecraft:swamp_hut, minecraft:village]

-- TerraForged ChunkGenerator --
Details:
	Seed: -1250478810
	Settings: {"miscellaneous":{"smoothLayerDecorator":true,"strataRegionSize":366,"strataDecorator":true,"oreCompatibleStoneOnly":true,"erosionDecorator":true,"plainStoneErosion":false,"naturalSnowDecorator":true,"customBiomeFeatures":true,"vanillaLakes":false,"vanillaSprings":true,"vanillaLavaLakes":true,"vanillaLavaSprings":true,"mountainBiomeUsage":0.4,"volcanoBiomeUsage":0.4},"dimensions":{"bedrockLayer":{"material":"minecraft:bedrock","minDepth":1,"variance":4},"dimensions":{"nether":"default","end":"default","includeExtraDimensions":true}},"structures":{"stronghold":{"distance":32,"spread":3,"count":128,"salt":0,"constrainToBiomes":false,"disabled":false},"structures":{"minecraft:bastion_remnant":{"spacing":27,"separation":4,"salt":30084232,"disabled":false},"minecraft:buried_treasure":{"spacing":1,"separation":0,"salt":0,"disabled":false},"minecraft:desert_pyramid":{"spacing":32,"separation":8,"salt":14357617,"disabled":false},"minecraft:endcity":{"spacing":20,"separation":11,"salt":10387313,"disabled":false},"minecraft:fortress":{"spacing":27,"separation":4,"salt":30084232,"disabled":false},"minecraft:igloo":{"spacing":32,"separation":8,"salt":14357618,"disabled":false},"minecraft:jungle_pyramid":{"spacing":32,"separation":8,"salt":14357619,"disabled":false},"minecraft:mansion":{"spacing":80,"separation":20,"salt":10387319,"disabled":false},"minecraft:mineshaft":{"spacing":1,"separation":0,"salt":0,"disabled":false},"minecraft:monument":{"spacing":32,"separation":5,"salt":10387313,"disabled":false},"minecraft:nether_fossil":{"spacing":2,"separation":1,"salt":14357921,"disabled":false},"minecraft:ocean_ruin":{"spacing":20,"separation":8,"salt":14357621,"disabled":false},"minecraft:pillager_outpost":{"spacing":32,"separation":8,"salt":165745296,"disabled":false},"minecraft:ruined_portal":{"spacing":40,"separation":15,"salt":34222644,"disabled":false},"minecraft:shipwreck":{"spacing":24,"separation":4,"salt":165745296,"disabled":false},"minecraft:stronghold":{"spacing":1,"separation":0,"salt":0,"disabled":false},"minecraft:swamp_hut":{"spacing":32,"separation":8,"salt":14357620,"disabled":false},"minecraft:village":{"spacing":32,"separation":8,"salt":10387312,"disabled":false}}},"world":{"continent":{"continentType":"MULTI_IMPROVED","continentShape":"EUCLIDEAN","continentScale":4463,"continentJitter":0.596,"continentSkipping":0.819,"continentSizeVariance":0.75,"continentNoiseOctaves":5,"continentNoiseGain":0.262,"continentNoiseLacunarity":4.329},"controlPoints":{"deepOcean":0.1,"shallowOcean":0.25,"beach":0.326,"coast":0.448,"inland":0.501},"properties":{"spawnType":"CONTINENT_CENTER","worldHeight":256,"seaLevel":63}},"climate":{"temperature":{"seedOffset":0,"scale":6,"falloff":2,"min":0.0,"max":0.98,"bias":0.05},"moisture":{"seedOffset":0,"scale":6,"falloff":1,"min":0.0,"max":1.0,"bias":0.0},"biomeShape":{"biomeSize":225,"macroNoiseSize":8,"biomeWarpScale":150,"biomeWarpStrength":80},"biomeEdgeShape":{"type":"SIMPLEX","scale":24,"octaves":2,"gain":0.5,"lacunarity":2.65,"strength":14}},"terrain":{"general":{"terrainSeedOffset":0,"terrainRegionSize":1200,"globalVerticalScale":0.494,"globalHorizontalScale":0.64,"fancyMountains":true},"steppe":{"weight":1.0,"baseScale":1.0,"verticalScale":0.0,"horizontalScale":1.0},"plains":{"weight":10.0,"baseScale":1.0,"verticalScale":7.603,"horizontalScale":1.0},"hills":{"weight":2.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"dales":{"weight":1.5,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"plateau":{"weight":1.5,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"badlands":{"weight":1.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"torridonian":{"weight":2.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"mountains":{"weight":2.5,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"volcano":{"weight":5.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0}},"rivers":{"seedOffset":0,"riverCount":8,"mainRivers":{"bedDepth":5,"minBankHeight":2,"maxBankHeight":6,"bedWidth":8,"bankWidth":20,"fade":0.75},"branchRivers":{"bedDepth":4,"minBankHeight":1,"maxBankHeight":4,"bedWidth":5,"bankWidth":14,"fade":0.975},"lakes":{"chance":0.3,"minStartDistance":0.0,"maxStartDistance":0.029,"depth":10,"sizeMin":75,"sizeMax":150,"minBankHeight":2,"maxBankHeight":10},"wetlands":{"chance":0.6,"sizeMin":175,"sizeMax":225}},"filters":{"erosion":{"dropletsPerChunk":135,"dropletLifetime":12,"dropletVolume":0.699,"dropletVelocity":0.699,"erosionRate":0.5,"depositeRate":0.5},"smoothing":{"iterations":4,"smoothingRadius":2.538,"smoothingRate":0.899}}}

-- TerraForged BiomeProvider --
Details:
	Overworld Biomes: [minecraft:badlands, minecraft:badlands_plateau, minecraft:bamboo_jungle, minecraft:beach, minecraft:birch_forest, terraforged:bryce, terraforged:cold_marshland, minecraft:cold_ocean, terraforged:cold_steppe, minecraft:dark_forest, minecraft:deep_cold_ocean, minecraft:deep_frozen_ocean, minecraft:deep_lukewarm_ocean, minecraft:deep_ocean, minecraft:deep_warm_ocean, minecraft:desert, minecraft:desert_lakes, minecraft:eroded_badlands, terraforged:fir_forest, minecraft:flower_forest, terraforged:flower_plains, minecraft:forest, terraforged:frozen_lake, terraforged:frozen_marsh, minecraft:frozen_ocean, minecraft:frozen_river, minecraft:giant_spruce_taiga, minecraft:giant_tree_taiga, minecraft:gravelly_mountains, minecraft:ice_spikes, minecraft:jungle, minecraft:jungle_edge, terraforged:lake, minecraft:lukewarm_ocean, terraforged:marshland, minecraft:modified_badlands_plateau, minecraft:modified_gravelly_mountains, minecraft:modified_jungle, minecraft:modified_jungle_edge, minecraft:modified_wooded_badlands_plateau, minecraft:mountains, minecraft:mushroom_field_shore, minecraft:mushroom_fields, minecraft:ocean, minecraft:plains, minecraft:river, minecraft:savanna, minecraft:savanna_plateau, terraforged:savanna_scrub, minecraft:shattered_savanna, minecraft:shattered_savanna_plateau, terraforged:shattered_savanna_scrub, minecraft:snowy_beach, terraforged:snowy_fir_forest, minecraft:snowy_mountains, minecraft:snowy_taiga, minecraft:snowy_taiga_mountains, minecraft:snowy_tundra, terraforged:steppe, terraforged:stone_forest, minecraft:stone_shore, minecraft:sunflower_plains, minecraft:swamp, minecraft:taiga, minecraft:taiga_mountains, terraforged:taiga_scrub, minecraft:tall_birch_forest, terraforged:warm_beach, minecraft:warm_ocean, minecraft:wooded_badlands_plateau, minecraft:wooded_mountains]

-- TerraForged Biome Weights Config --
Details:
	terraforged:example_biome: 10

-- TerraForged Profiler --
Details:
	Timings: 
		Section             Count      Time MS    Min MS     Max MS     Average MS
		structure_starts    29658      7911       0          1651       0.27
		structure_refs      880        117        0          1          0.13
		biomes              29259      25101      0          1221       0.86
		terrain             29259      49757      1          118        1.70
		surface             29259      13589      0          64         0.46
		air_carvers         880        622        0          154        0.71
		fluid_carvers       880        455        0          245        0.52
		decoration          29112      85072      0          405        2.92
		mob_spawns          761        100        0          12         0.13
		structure_searches  0          0          0          0          0.00
		Sum                                                             7.70

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6277437008 bytes (5986 MB) / 8589934592 bytes (8192 MB) up to 15032385536 bytes (14336 MB)
	CPUs: 16
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx14G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		DistantHorizons-1.6.0a-1.16.5.jar                 |Distant Horizons              |lod                           |1.6.0a              |DONE      |Manifest: NOSIGNATURE
		TrackAPI-1.16.4-forge-1.2.1.jar                   |TrackAPI                      |trackapi                      |1.2                 |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		ImmersiveEngineering-1.16.5-5.1.0-148.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.1.0-148    |DONE      |Manifest: NOSIGNATURE
		controllable-0.13.3-1.16.3.jar                    |Controllable                  |controllable                  |0.13.3              |DONE      |Manifest: e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		TerraForged-1.16.5-0.2.16.jar                     |TerraForged                   |terraforged                   |0.2.16              |DONE      |Manifest: 7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		ImmersiveRailroading-1.16.5-forge-1.9.1.jar       |Immersive Railroading         |immersiverailroading          |1.16.5-forge-1.9.1  |DONE      |Manifest: NOSIGNATURE
		UniversalModCore-1.16.5-forge-1.1.3.jar           |Universal Mod Core            |universalmodcore              |1.1.3               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: f2781d65-8fa5-4e16-9fb6-9ee2ada32ea7
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14761 Compatibility Profile Context 21.30.02.13 30.0.13002.13003
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 16

**Comment by Won-Ton** [comment]
Yep the crash is caused by distant horizons. They multi-thread some of their code to reduce lag but they're accessing some vanilla code that isn't safe to be used in multiple threads at once.

IIRC they have an option to disable multithreading that you could try.
