### ISSUE TITLE
Re: Fatal Server crash

### ISSUE THREAD

**Issue by rsslcs** [TerraForged/tracker#82]
Hi @Won-Ton; Sorry to post another issue, but I had no other way to respond, given that comments are locked, and I cannot find any community. The Geolosys dev had a look at it first, but couldn't identify the problem. Would you have any insight into what's the issue? Is there any info I could provide that may make that easier? :) Thanks a lot!

**Comment by Won-Ton** [comment]
Their feature `PlutonOreFeature` is trying to place blocks outside of the region of chunks that are currently generating.

```
Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | -222 -414
	at net.minecraft.world.gen.WorldGenRegion.func_217353_a(WorldGenRegion.java:131) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:112) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.WorldGenRegion.func_212866_a_(WorldGenRegion.java:106) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.WorldGenRegion.func_180495_p(WorldGenRegion.java:141) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.terraforged.mod.chunk.fix.RegionDelegate.func_180495_p(RegionDelegate.java:115) ~[terraforged:1.16.4-0.2.9] {re:classloading,pl:runtimedistcleaner:A}
	at com.oitsjustjose.geolosys.common.world.feature.FeatureUtils.generateLayer(FeatureUtils.java:240) ~[geolosys:5.1.1] {re:classloading}
	at com.oitsjustjose.geolosys.common.world.feature.PlutonOreFeature.func_207803_a(PlutonOreFeature.java:202) ~[geolosys:5.1.1] {re:classloading}
```
